import fs from 'fs';
import path from 'path';

const filePath = path.resolve('src/context/ShopContext.jsx');
let content = fs.readFileSync(filePath, 'utf-8');

const newTranslations = {
  EN: {
    gender: "Gender",
    recipient_filter: "Recipient",
    color_family: "Color Family",
    size_bracket: "Size Bracket",
    price_budget: "Price Budget",
    min_rating: "Minimum Rating",
    min_discount: "Minimum Discount",
    all_genders: "All Genders",
    men: "Men",
    women: "Women",
    all_recipients: "All Recipients",
    for_him: "For Him",
    for_her: "For Her",
    couples_both: "Couples & Both",
    for_kids_teens: "For Kids & Teens",
    for_friends_coworkers: "For Friends & Coworkers",
    self_care: "Self-Care & Treat Yourself",
    all_occasions: "All Occasions",
    birthdays: "Birthdays",
    anniversaries: "Anniversaries",
    housewarming: "Housewarming",
    graduation: "Graduation",
    weddings_bridal: "Weddings & Bridal",
    festivals_holidays: "Festivals & Holidays",
    corporate_milestones: "Corporate & Milestones",
    all_colors: "All Colors",
    color_black: "Dark / Black",
    color_white: "Light / White",
    color_brown: "Tones / Brown",
    color_green: "Sage / Green",
    color_blue: "Navy / Blue",
    all_sizes: "All Sizes",
    size_standard: "Standard / One-Size",
    size_small: "Small / Travel",
    size_medium: "Medium",
    size_large: "Large / Luxury",
    any_price: "Any Price",
    under_price: "Under {price}",
    price_range: "{min} - {max}",
    over_price: "Over {price}",
    show_all_listings: "Show All Listings",
    all_reviews: "All Reviews",
    stars_and_up: "{rating}+ Stars",
    stars_only: "{rating} Stars Only",
    all_items_no_min: "All Items (No Min)",
    off_or_more: "{percent}% Off or More",
    discover_premium_selection: "Discover our premium selection across standard departments. From cutting-edge electronics to high fashion, we have got you covered.",
    all_brands: "All Brands",
    active_filters: "Active Filters",
    reset_filters: "Reset Filters",
    filter_by: "Filter by",
    sort_by: "Sort by",
    featured: "Featured",
    price_low_high: "Price: Low to High",
    price_high_low: "Price: High to Low",
    gomo_smart_assistant: "GoMo Smart Assistant",
    smart_assistant_desc: "Find your ideal matching products through personalized suggestions.",
    question_step: "Question {current} of {total}",
    which_department: "Which department are you shopping in?",
    electronics_tech: "Electronics & Tech",
    fashion_apparel: "Fashion & Apparel",
    home_kitchen: "Home & Kitchen",
    books_stationery: "Books & Stationery",
    beauty_grooming: "Beauty & Grooming",
    primary_preference: "What is your primary preference?",
    premium_quality_design: "Premium Quality & Design",
    utility_high_value: "Utility & High Value",
    new_arrivals_trending: "New Arrivals & Trending",
    top_rated_best_sellers: "Top Rated & Best Sellers",
    budget_tier: "What is your budget tier?",
    budget_value: "Value (Under {price})",
    budget_mid: "Mid-range ({min} - {max})",
    budget_premium: "Premium ({price} +)",
    recommended_for_you_finder: "Recommended for You",
    based_on_preferences: "Based on your preferences, we suggest these exceptional products.",
    no_products_finder: "No products matching current selection."
  },
  HI: {
    gender: "लिंग",
    recipient_filter: "प्राप्तकर्ता",
    color_family: "रंग",
    size_bracket: "आकार",
    price_budget: "बजट",
    min_rating: "न्यूनतम रेटिंग",
    min_discount: "न्यूनतम छूट",
    all_genders: "सभी लिंग",
    men: "पुरुष",
    women: "महिला",
    all_recipients: "सभी प्राप्तकर्ता",
    for_him: "उनके लिए (पुरुष)",
    for_her: "उनके लिए (महिला)",
    couples_both: "जोड़े और दोनों",
    for_kids_teens: "बच्चों और किशोरों के लिए",
    for_friends_coworkers: "दोस्तों और सहकर्मियों के लिए",
    self_care: "स्वयं की देखभाल",
    all_occasions: "सभी अवसर",
    birthdays: "जन्मदिन",
    anniversaries: "वर्षगांठ",
    housewarming: "गृहप्रवेश",
    graduation: "समारोह",
    weddings_bridal: "शादी और दुल्हन",
    festivals_holidays: "त्यौहार और छुट्टियाँ",
    corporate_milestones: "कॉर्पोरेट और मील के पत्थर",
    all_colors: "सभी रंग",
    color_black: "डार्क / काला",
    color_white: "लाइट / सफेद",
    color_brown: "ब्राउन / टोन",
    color_green: "हरा / सेज",
    color_blue: "नेवी / नीला",
    all_sizes: "सभी आकार",
    size_standard: "मानक / एक-आकार",
    size_small: "छोटा / यात्रा",
    size_medium: "मध्यम",
    size_large: "बड़ा / लक्जरी",
    any_price: "कोई भी कीमत",
    under_price: "{price} से कम",
    price_range: "{min} - {max}",
    over_price: "{price} से अधिक",
    show_all_listings: "सभी लिस्टिंग दिखाएं",
    all_reviews: "सभी समीक्षाएं",
    stars_and_up: "{rating}+ स्टार",
    stars_only: "{rating} स्टार केवल",
    all_items_no_min: "सभी आइटम (कोई न्यूनतम नहीं)",
    off_or_more: "{percent}% या अधिक छूट",
    discover_premium_selection: "मानक विभागों में हमारे प्रीमियम चयन की खोज करें। अत्याधुनिक इलेक्ट्रॉनिक्स से लेकर उच्च फैशन तक, हमारे पास सब कुछ है।",
    all_brands: "सभी ब्रांड",
    active_filters: "सक्रिय फ़िल्टर",
    reset_filters: "फ़िल्टर रीसेट करें",
    filter_by: "फ़िल्टर करें",
    sort_by: "क्रमबद्ध करें",
    featured: "विशेष रुप से प्रदर्शित",
    price_low_high: "कीमत: कम से अधिक",
    price_high_low: "कीमत: अधिक से कम",
    gomo_smart_assistant: "गोमो स्मार्ट सहायक",
    smart_assistant_desc: "व्यक्तिगत सुझावों के माध्यम से अपने आदर्श मिलान वाले उत्पाद खोजें।",
    question_step: "प्रश्न {current} का {total}",
    which_department: "आप किस विभाग में खरीदारी कर रहे हैं?",
    electronics_tech: "इलेक्ट्रॉनिक्स और टेक",
    fashion_apparel: "फैशन और परिधान",
    home_kitchen: "घर और रसोई",
    books_stationery: "पुस्तकें और स्टेशनरी",
    beauty_grooming: "सौंदर्य और ग्रूमिंग",
    primary_preference: "आपकी प्राथमिक प्राथमिकता क्या है?",
    premium_quality_design: "प्रीमियम गुणवत्ता और डिज़ाइन",
    utility_high_value: "उपयोगिता और उच्च मूल्य",
    new_arrivals_trending: "नए आगमन और ट्रेंडिंग",
    top_rated_best_sellers: "टॉप रेटेड और बेस्ट सेलर्स",
    budget_tier: "आपका बजट स्तर क्या है?",
    budget_value: "मूल्य ({price} से कम)",
    budget_mid: "मध्यम श्रेणी ({min} - {max})",
    budget_premium: "प्रीमियम ({price} +)",
    recommended_for_you_finder: "आपके लिए अनुशंसित",
    based_on_preferences: "आपकी प्राथमिकताओं के आधार पर, हम इन असाधारण उत्पादों का सुझाव देते हैं।",
    no_products_finder: "वर्तमान चयन से मेल खाने वाले कोई उत्पाद नहीं हैं।"
  },
  ES: {
    gender: "Género",
    recipient_filter: "Destinatario",
    color_family: "Color",
    size_bracket: "Talla",
    price_budget: "Presupuesto",
    min_rating: "Calificación Mínima",
    min_discount: "Descuento Mínimo",
    all_genders: "Todos los Géneros",
    men: "Hombres",
    women: "Mujeres",
    all_recipients: "Todos los Destinatarios",
    for_him: "Para Él",
    for_her: "Para Ella",
    couples_both: "Parejas y Ambos",
    for_kids_teens: "Para Niños y Adolescentes",
    for_friends_coworkers: "Para Amigos y Compañeros",
    self_care: "Cuidado Personal",
    all_occasions: "Todas las Ocasiones",
    birthdays: "Cumpleaños",
    anniversaries: "Aniversarios",
    housewarming: "Inauguración de Casa",
    graduation: "Graduación",
    weddings_bridal: "Bodas y Novias",
    festivals_holidays: "Festivales y Fiestas",
    corporate_milestones: "Corporativo y Logros",
    all_colors: "Todos los Colores",
    color_black: "Oscuro / Negro",
    color_white: "Claro / Blanco",
    color_brown: "Marrón / Tonos",
    color_green: "Verde / Sage",
    color_blue: "Azul / Marino",
    all_sizes: "Todas las Tallas",
    size_standard: "Estándar / Única",
    size_small: "Pequeña / Viaje",
    size_medium: "Mediana",
    size_large: "Grande / Lujo",
    any_price: "Cualquier Precio",
    under_price: "Menos de {price}",
    price_range: "{min} - {max}",
    over_price: "Más de {price}",
    show_all_listings: "Ver Todos los Productos",
    all_reviews: "Todas las Opiniones",
    stars_and_up: "{rating}+ Estrellas",
    stars_only: "{rating} Estrellas Solamente",
    all_items_no_min: "Todo (Sin Mínimo)",
    off_or_more: "{percent}% de Descuento o Más",
    discover_premium_selection: "Descubra nuestra selección premium en todos los departamentos. Desde electrónica de vanguardia hasta alta moda, lo tenemos cubierto.",
    all_brands: "Todas las Marcas",
    active_filters: "Filtros Activos",
    reset_filters: "Restablecer Filtros",
    filter_by: "Filtrar por",
    sort_by: "Ordenar por",
    featured: "Destacados",
    price_low_high: "Precio: de Menor a Mayor",
    price_high_low: "Precio: de Mayor a Menor",
    gomo_smart_assistant: "Asistente Inteligente GoMo",
    smart_assistant_desc: "Encuentre sus productos ideales a través de sugerencias personalizadas.",
    question_step: "Pregunta {current} de {total}",
    which_department: "¿En qué departamento está comprando?",
    electronics_tech: "Electrónica y Tecnología",
    fashion_apparel: "Moda y Ropa",
    home_kitchen: "Hogar y Cocina",
    books_stationery: "Libros y Papelería",
    beauty_grooming: "Belleza y Cuidado",
    primary_preference: "¿Cuál es su preferencia principal?",
    premium_quality_design: "Calidad y Diseño Premium",
    utility_high_value: "Utilidad y Alto Valor",
    new_arrivals_trending: "Novedades y Tendencias",
    top_rated_best_sellers: "Más Valorados y Vendidos",
    budget_tier: "¿Cuál es su rango de presupuesto?",
    budget_value: "Económico (Menos de {price})",
    budget_mid: "Gama Media ({min} - {max})",
    budget_premium: "Premium ({price} +)",
    recommended_for_you_finder: "Recomendado para Usted",
    based_on_preferences: "Según sus preferencias, le sugerimos estos productos excepcionales.",
    no_products_finder: "No hay productos que coincidan con la selección actual."
  },
  FR: {
    gender: "Genre",
    recipient_filter: "Destinataire",
    color_family: "Couleur",
    size_bracket: "Taille",
    price_budget: "Budget",
    min_rating: "Note Minimale",
    min_discount: "Remise Minimale",
    all_genders: "Tous les Genres",
    men: "Hommes",
    women: "Femmes",
    all_recipients: "Tous les Destinataires",
    for_him: "Pour Lui",
    for_her: "Pour Elle",
    couples_both: "Couples & Les Deux",
    for_kids_teens: "Pour Enfants & Ados",
    for_friends_coworkers: "Pour Amis & Collègues",
    self_care: "Soin de Soi",
    all_occasions: "Toutes les Occasions",
    birthdays: "Anniversaires",
    anniversaries: "Anniversaires de Mariage",
    housewarming: "Crémaillère",
    graduation: "Remise de Diplôme",
    weddings_bridal: "Mariages & Mariées",
    festivals_holidays: "Festivals & Fêtes",
    corporate_milestones: "Entreprise & Jalons",
    all_colors: "Toutes les Couleurs",
    color_black: "Sombre / Noir",
    color_white: "Clair / Blanc",
    color_brown: "Brun / Tons Chauds",
    color_green: "Sauge / Vert",
    color_blue: "Bleu / Marine",
    all_sizes: "Toutes les Tailles",
    size_standard: "Standard / Unique",
    size_small: "Petit / Voyage",
    size_medium: "Moyen",
    size_large: "Grand / Luxe",
    any_price: "Tout Prix",
    under_price: "Moins de {price}",
    price_range: "{min} - {max}",
    over_price: "Plus de {price}",
    show_all_listings: "Voir Tous les Produits",
    all_reviews: "Tous les Avis",
    stars_and_up: "{rating}+ Étoiles",
    stars_only: "{rating} Étoiles Uniquement",
    all_items_no_min: "Tout (Sans Minimum)",
    off_or_more: "{percent}% de Réduction ou Plus",
    discover_premium_selection: "Découvrez notre sélection premium dans tous les départements. De l'électronique de pointe à la haute couture, nous avons ce qu'il vous faut.",
    all_brands: "Toutes les Marques",
    active_filters: "Filtres Actifs",
    reset_filters: "Réinitialiser",
    filter_by: "Filtrer par",
    sort_by: "Trier par",
    featured: "En Vedette",
    price_low_high: "Prix : Ordre Croissant",
    price_high_low: "Prix : Ordre Décroissant",
    gomo_smart_assistant: "Assistant Intelligent GoMo",
    smart_assistant_desc: "Trouvez vos produits idéaux grâce à des suggestions personnalisées.",
    question_step: "Question {current} sur {total}",
    which_department: "Dans quel département achetez-vous ?",
    electronics_tech: "Électronique & Technologie",
    fashion_apparel: "Mode & Vêtements",
    home_kitchen: "Maison & Cuisine",
    books_stationery: "Livres & Papeterie",
    beauty_grooming: "Beauté & Soins",
    primary_preference: "Quelle est votre préférence principale ?",
    premium_quality_design: "Qualité & Design Premium",
    utility_high_value: "Utilité & Haute Valeur",
    new_arrivals_trending: "Nouveautés & Tendances",
    top_rated_best_sellers: "Mieux Notés & Ventes",
    budget_tier: "Quel est votre budget ?",
    budget_value: "Économique (Moins de {price})",
    budget_mid: "Milieu de Gamme ({min} - {max})",
    budget_premium: "Premium ({price} +)",
    recommended_for_you_finder: "Recommandé pour Vous",
    based_on_preferences: "Selon vos préférences, nous vous suggérons ces produits exceptionnels.",
    no_products_finder: "Aucun produit ne correspond à la sélection actuelle."
  },
  DE: {
    gender: "Geschlecht",
    recipient_filter: "Empfänger",
    color_family: "Farbe",
    size_bracket: "Größe",
    price_budget: "Budget",
    min_rating: "Mindestbewertung",
    min_discount: "Mindestrabatt",
    all_genders: "Alle Geschlechter",
    men: "Herren",
    women: "Damen",
    all_recipients: "Alle Empfänger",
    for_him: "Für Ihn",
    for_her: "Für Sie (Damen)",
    couples_both: "Paare & Beide",
    for_kids_teens: "Für Kinder & Jugendliche",
    for_friends_coworkers: "Für Freunde & Kollegen",
    self_care: "Selbstpflege",
    all_occasions: "Alle Anlässe",
    birthdays: "Geburtstage",
    anniversaries: "Jahrestage",
    housewarming: "Einweihungsfeier",
    graduation: "Abschlussfeier",
    weddings_bridal: "Hochzeiten & Brautmoden",
    festivals_holidays: "Feste & Feiertage",
    corporate_milestones: "Firmen- & Meilensteine",
    all_colors: "Alle Farben",
    color_black: "Dunkel / Schwarz",
    color_white: "Hell / Weiß",
    color_brown: "Brauntöne / Braun",
    color_green: "Salbei / Grün",
    color_blue: "Marine / Blau",
    all_sizes: "Alle Größen",
    size_standard: "Standard / Einheitsgröße",
    size_small: "Klein / Reise",
    size_medium: "Mittel",
    size_large: "Groß / Luxus",
    any_price: "Jeder Preis",
    under_price: "Unter {price}",
    price_range: "{min} - {max}",
    over_price: "Über {price}",
    show_all_listings: "Alle Artikel anzeigen",
    all_reviews: "Alle Bewertungen",
    stars_and_up: "{rating}+ Sterne & Mehr",
    stars_only: "Nur {rating} Sterne",
    all_items_no_min: "Alle (Kein Minimum)",
    off_or_more: "{percent}% Rabatt oder mehr",
    discover_premium_selection: "Entdecken Sie unsere Premium-Auswahl in allen Kategorien. Von modernster Elektronik bis hin zu High Fashion – wir haben alles für Sie.",
    all_brands: "Alle Marken",
    active_filters: "Aktive Filter",
    reset_filters: "Zurücksetzen",
    filter_by: "Filtern nach",
    sort_by: "Sortieren nach",
    featured: "Empfohlen",
    price_low_high: "Preis: Aufsteigend",
    price_high_low: "Preis: Absteigend",
    gomo_smart_assistant: "GoMo Intelligenter Assistent",
    smart_assistant_desc: "Finden Sie Ihre idealen Produkte durch personalisierte Vorschläge.",
    question_step: "Frage {current} von {total}",
    which_department: "In welcher Kategorie suchen Sie?",
    electronics_tech: "Elektronik & Technik",
    fashion_apparel: "Mode & Bekleidung",
    home_kitchen: "Wohnen & Küche",
    books_stationery: "Bücher & Schreibwaren",
    beauty_grooming: "Schönheit & Pflege",
    primary_preference: "Was ist Ihre Hauptpräferenz?",
    premium_quality_design: "Premium-Qualität & Design",
    utility_high_value: "Nützlichkeit & Hoher Wert",
    new_arrivals_trending: "Neuheiten & Trends",
    top_rated_best_sellers: "Top-Bewertet & Bestseller",
    budget_tier: "Wie hoch ist Ihr Budget?",
    budget_value: "Günstig (Unter {price})",
    budget_mid: "Mittleres Segment ({min} - {max})",
    budget_premium: "Premium ({price} +)",
    recommended_for_you_finder: "Für Sie empfohlen",
    based_on_preferences: "Basierend auf Ihren Wünschen empfehlen wir diese außergewöhnlichen Produkte.",
    no_products_finder: "Keine Produkte entsprechen der aktuellen Auswahl."
  },
  JA: {
    gender: "性別",
    recipient_filter: "ギフトの対象",
    color_family: "カラー系統",
    size_bracket: "サイズ区分",
    price_budget: "予算帯",
    min_rating: "最低評価",
    min_discount: "最低割引率",
    all_genders: "すべての性別",
    men: "メンズ",
    women: "レディース",
    all_recipients: "すべての対象者",
    for_him: "彼向け・メンズ",
    for_her: "彼女向け・レディース",
    couples_both: "カップル・両者向け",
    for_kids_teens: "キッズ＆ティーン向け",
    for_friends_coworkers: "友人＆同僚向け",
    self_care: "セルフケア・自分へのご褒美",
    all_occasions: "すべてのイベント",
    birthdays: "誕生日",
    anniversaries: "記念日",
    housewarming: "新築祝い",
    graduation: "卒業・昇進祝い",
    weddings_bridal: "結婚式＆ブライダル",
    festivals_holidays: "季節の祝祭＆休日",
    corporate_milestones: "企業イベント＆目標達成",
    all_colors: "すべてのカラー",
    color_black: "ダーク・ブラック系統",
    color_white: "ライト・ホワイト系統",
    color_brown: "ブラウン・アース系統",
    color_green: "セージ・グリーン系統",
    color_blue: "ネイビー・ブルー系統",
    all_sizes: "すべてのサイズ",
    size_standard: "標準・フリーサイズ",
    size_small: "スモール・旅行用",
    size_medium: "ミディアムサイズ",
    size_large: "ラージ・ラグジュアリー",
    any_price: "すべての価格帯",
    under_price: "{price} 以下",
    price_range: "{min} - {max}",
    over_price: "{price} 以上",
    show_all_listings: "すべての出品を表示",
    all_reviews: "すべてのレビュー",
    stars_and_up: "星 {rating} つ以上",
    stars_only: "星 {rating} つのみ",
    all_items_no_min: "すべての商品（下限なし）",
    off_or_more: "{percent}% 以上オフ",
    discover_premium_selection: "主要部門から厳選されたプレミアムな商品をご紹介します。最先端の家電からハイファッションまで幅広く取り揃えています。",
    all_brands: "すべてのブランド",
    active_filters: "適用中のフィルター",
    reset_filters: "クリアする",
    filter_by: "絞り込み",
    sort_by: "並べ替え",
    featured: "おすすめ順",
    price_low_high: "価格の安い順",
    price_high_low: "価格の高い順",
    gomo_smart_assistant: "GoMo スマートアシスタント",
    smart_assistant_desc: "いくつかの質問に答えるだけで、あなたにぴったりの商品をご提案します。",
    question_step: "質問 {current} / {total}",
    which_department: "どの部門の商品をお探しですか？",
    electronics_tech: "家電・ガジェット・PC",
    fashion_apparel: "ファッション・衣類",
    home_kitchen: "ホーム・キッチン・生活雑貨",
    books_stationery: "本・書籍・ステーショナリー",
    beauty_grooming: "ビューティー・コスメ・ヘルスケア",
    primary_preference: "重視するポイントはどれですか？",
    premium_quality_design: "最高品質のこだわりデザイン",
    utility_high_value: "実用性・コスパ重視",
    new_arrivals_trending: "最新トレンド・新着アイテム",
    top_rated_best_sellers: "高評価レビュー・ベストセラー",
    budget_tier: "ご予算はどのくらいですか？",
    budget_value: "お手頃価格 ({price} 未満)",
    budget_mid: "ミドルレンジ ({min} - {max})",
    budget_premium: "プレミアム・高級ライン ({price} 以上)",
    recommended_for_you_finder: "あなたへのおすすめ商品",
    based_on_preferences: "ご提案いただいた条件に基づき、こちらの最適な商品をご提案します。",
    no_products_finder: "選択した条件に一致する商品は見つかりませんでした。"
  },
  AR: {
    gender: "الجنس",
    recipient_filter: "المستلم",
    color_family: "مجموعة الألوان",
    size_bracket: "فئة المقاس",
    price_budget: "ميزانية السعر",
    min_rating: "الحد الأدنى للتقييم",
    min_discount: "الحد الأدنى للخصم",
    all_genders: "جميع الجنسين",
    men: "رجالي",
    women: "نسائي",
    all_recipients: "جميع المستلمين",
    for_him: "له (رجالي)",
    for_her: "لها (نسائي)",
    couples_both: "للأزواج وكلا الطرفين",
    for_kids_teens: "للأطفال والمراهقين",
    for_friends_coworkers: "للأصدقاء والزملاء",
    self_care: "عناية شخصية وإهداء ذاتي",
    all_occasions: "جميع المناسبات",
    birthdays: "أعياد ميلاد",
    anniversaries: "ذكرى سنوية",
    housewarming: "منزل جديد",
    graduation: "تخرج",
    weddings_bridal: "حفلات زفاف وعرائس",
    festivals_holidays: "مهرجانات وأعياد",
    corporate_milestones: "إنجازات شركات وأعمال",
    all_colors: "جميع الألوان",
    color_black: "داكن / أسود",
    color_white: "فاتح / أبيض",
    color_brown: "بني / درجات خشبية",
    color_green: "أخضر / زيتوني",
    color_blue: "أزرق / كحلي",
    all_sizes: "جميع المقاسات",
    size_standard: "مقاس موحد / قياسي",
    size_small: "صغير / حجم السفر",
    size_medium: "متوسط",
    size_large: "كبير / فاخر",
    any_price: "أي سعر",
    under_price: "أقل من {price}",
    price_range: "{min} - {max}",
    over_price: "أكثر من {price}",
    show_all_listings: "عرض كافة المنتجات",
    all_reviews: "كافة التقييمات",
    stars_and_up: "{rating}+ نجوم وأعلى",
    stars_only: "{rating} نجوم فقط",
    all_items_no_min: "كافة المنتجات (بدون حد أدنى)",
    off_or_more: "خصم {percent}% أو أكثر",
    discover_premium_selection: "اكتشف تشكيلتنا المتميزة عبر الأقسام المختلفة. نوفر لك كل ما تحتاجه من الإلكترونيات الحديثة إلى أرقى صيحات الموضة.",
    all_brands: "كافة العلامات التجارية",
    active_filters: "الفلاتر النشطة",
    reset_filters: "إعادة ضبط",
    filter_by: "تصفية حسب",
    sort_by: "ترتيب حسب",
    featured: "المميز",
    price_low_high: "السعر: من الأقل للأعلى",
    price_high_low: "السعر: من الأعلى للأقل",
    gomo_smart_assistant: "مساعد GoMo الذكي",
    smart_assistant_desc: "ابحث عن منتجاتك المثالية بناءً على تفضيلاتك الفردية.",
    question_step: "السؤال {current} من {total}",
    which_department: "ما القسم الذي تتسوق فيه؟",
    electronics_tech: "الإلكترونيات والتقنية",
    fashion_apparel: "الأزياء والملابس",
    home_kitchen: "المنزل والمطبخ",
    books_stationery: "الكتب والأدوات المكتبية",
    beauty_grooming: "الجمال والعناية الشخصية",
    primary_preference: "ما هي أولويتك المفضلة؟",
    premium_quality_design: "جودة وتصميم فاخر",
    utility_high_value: "عملي وقيمة عالية",
    new_arrivals_trending: "وصول جديد وأحدث الصيحات",
    top_rated_best_sellers: "الأعلى تقييماً والأكثر مبيعاً",
    budget_tier: "ما فئة الميزانية الخاصة بك؟",
    budget_value: "اقتصادي (تحت {price})",
    budget_mid: "فئة متوسطة ({min} - {max})",
    budget_premium: "فاخر ({price} +)",
    recommended_for_you_finder: "موصى به لك",
    based_on_preferences: "بناءً على اختياراتك، نقترح عليك هذه المنتجات الاستثنائية.",
    no_products_finder: "لم يتم العثور على منتجات تطابق الاختيارات الحالية."
  }
};

// Perform injection replacement
const languageKeys = Object.keys(newTranslations);
for (const lang of languageKeys) {
  let departmentsPattern = '';
  let replacement = '';
  
  if (lang === 'EN') {
    departmentsPattern = 'departments: "Departments"';
  } else if (lang === 'HI') {
    departmentsPattern = 'departments: "विभागों"';
  } else if (lang === 'ES') {
    departmentsPattern = 'departments: "Departamentos"';
  } else if (lang === 'FR') {
    departmentsPattern = 'departments: "Départements"';
  } else if (lang === 'DE') {
    departmentsPattern = 'departments: "Kategorien"';
  } else if (lang === 'JA') {
    departmentsPattern = 'departments: "部門カテゴリ"';
  } else if (lang === 'AR') {
    departmentsPattern = 'departments: "الأقسام"';
  }
  
  // Format the translation keys for the current language
  const keysStr = Object.entries(newTranslations[lang])
    .map(([k, v]) => `    ${k}: ${JSON.stringify(v)}`)
    .join(',\n');
    
  replacement = `${departmentsPattern},\n${keysStr}`;
  content = content.replace(departmentsPattern, replacement);
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log("Translations dictionary extended successfully!");
